cass_error: MetadataError better conversion
`MetadataFetchErrorKind::NextRowError` was previously always converted
to `CassError::CASS_ERROR_LIB_UNEXPECTED_RESPONSE`, which is not
appropriate for all cases. This commit refactors the conversion to
handle different cases of `NextRowError` more appropriately, depending
on the specific error encountered.