cass_error: replace `UNABLE_TO_CONNECT` with `NO_HOSTS_AVAILABLE`
Motivation (based on cpp-driver):
1. UNABLE_TO_CONNECT should only be returned when user tries to call
   `cass_session_connect` on a session that is already connecting, connected or closing.
   We already handle this case in `session.rs`.

```
        let mut session_guard = session_opt.write().await;
        if session_guard.is_some() {
            return Err((
                CassError::CASS_ERROR_LIB_UNABLE_TO_CONNECT,
                "Already connecting, closing, or connected".msg(),
            ));
        }
```

2. NO_HOSTS_AVAILABLE is returned in all places where driver cannot reach
   one of the nodes. This includes:
   - pool is broken
   - connection is broken
   - connection is closed
   - connection is refused
   - empty LB plan
   - user provided empty list of contact points
   ... etc.

Thanks to this change, we will also be able to enable new integration tests
that expect `NO_HOSTS_AVAILABLE` error.

As a side note: as you can see, the NO_HOST_AVAILABLE is mapped from a lot of
Rust error types/variants. I believe we should increase the granularity of
CassError enum and add more error variants. This way we will be able to
define more direct mapping between Rust and cpp-rust-driver errors.